name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's SSH private key
          port: ${{ secrets.PORT }} # SSH PORT
          script: |
            cd /var/www/wwa-rent-scraper
            git pull
            npm ci
            npx prisma generate
            npx prisma migrate deploy
            npx playwright install chromium
            npm run build
            pm2 restart ecosystem.config.js
